name: Tic-Tac-Toe Automation

on:
  push:
    branches: [TicTacToe_automated]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version

TicTacToe_automated:
      - name: Run tests
        run: Code.py tests/ -v
